variant: fcos
version: 1.3.0
passwd:
  users:
    - name: altcos
      groups:
        - wheel
        - docker
      password_hash: $y$j9T$ZEYmKSGPiNFOZNTjvobEm1$IXLGt5TxdNC/OhJyzFK5NVM.mt6VvdtP6mhhzSmvE94

storage:
  files:

    - path: /etc/zincati/config.d/10-agent.toml
      overwrite: true
      mode: 0644
      user:
        name: root
      group:
        name: root
      contents:
        inline: |
          # Configure agent timing.
          [agent.timing]
          # Pausing interval between updates checks in steady mode, in seconds.
          steady_interval_secs = 60


    - path: /etc/zincati/config.d/50-altcos-cincinnati.toml
      overwrite: true
      mode: 0644
      user:
        name: root
      group:
        name: root
      contents:
        inline: |
          [cincinnati]
          base_url="https://altcos.altlinux.org/barearchive/"

    - path: /etc/ostree/remotes.d/altcos.conf
      overwrite: true
      mode: 0644
      user:
        name: root
      group:
        name: root
      contents:
        inline: |
          [remote "altcos"]
          url=https://altcos.altlinux.org/ALTCOS/streams/altcos/x86_64/sisyphus/barearchive/repo/
          gpg-verify=false
