version: 2.0.0
actions:
  - rpms:
      cri-o:
      kubernetes-kubeadm:
      kubernetes-kubelet:
      kubernetes-crio:
      cri-tools:
      bash-completion:
      yq:
      jq:
      tzdata:
      net-tools:
  - env:
      Images:
        cmd: kubeadm config images list --kubernetes-version latest
      imageList: "$Images quay.io/coreos/flannel:v0.15.1"
      CONSTANT: "Моя константа"
  - podman:
      envListImages: Images
      images:
        - docker.io/rancher/mirrored-flannelcni-flannel-cni-plugin:v1.0.0
        - quay.io/coreos/flannel:v0.15.1

  - run:
    - /var/www/vhosts/altcos/ostree/bin/skopeo_copy.sh $MERGEDIR `kubeadm config images list --kubernetes-version latest`
