variant: fcos
version: 1.3.0

storage:
  trees:
    - local: root
      path: /
  files:
    - path: /bin/loadDockerArchiveImages.sh
      mode: 0755
      overwrite: true
    - path: /etc/systemd/system/kubelet.service.d/kubeadm.conf
      overwrite: true


systemd:
  units:
    - name: crio.service
      enabled: true
    - name: kubelet.service
      enabled: true
    - name: kube-proxy.service
      enabled: true
