variant: fcos
version: 1.3.0

storage:
  directories:
    - path: /usr/share/k8s/flannel
  trees:
    - local: root
      path: /
  files:
    - path: /bin/loadDockerArchiveImages.sh
      mode: 0755
      overwrite: true
    - path: /etc/systemd/system/kubelet.service.d/kubeadm.conf
      overwrite: true
    - path:  /usr/share/k8s/flannel/kube-flannel.yml
      contents:
        source: https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml


systemd:
  units:
    - name: crio.service
      enabled: true
    - name: kubelet.service
      enabled: true
    - name: kube-proxy.service
      enabled: true
